# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.6
  - 7.0
  
matrix:
  fast_finish: true
  include:
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - hhvm

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

# Cache dependencies
cache:
  directories:
    - $HOME/.composer/cache

# Dependencies
before_install:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

before_script:
  - phpenv config-rm xdebug.ini || return 0

script:
  - composer test
  - composer lint -- --diff --dry-run -vvv

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7e5d662086972567218
    on_success: change
    on_failure: always
    on_start: false
