# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

# Special environments
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
  include:
    - php: 5.4
      env: dependencies=lowest

# Dependencies
before_script:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;


script: phpunit

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
