language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

install: travis_retry composer install --no-interaction --prefer-source --dev

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

script: phpunit
