# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.6
  - 7.0
  - hhvm-3.9

matrix:
  allow_failures:
    - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# Dependencies
before_install:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-interaction --prefer-dist $PREFER_LOWEST

before_script:
  - phpenv config-rm xdebug.ini

script:
  - composer test
  - composer lint -- --diff --dry-run -vvv

# Cache dependencies
cache:
  directories:
    - $HOME/.composer/cache

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7e5d662086972567218
    on_success: change
    on_failure: always
    on_start: false
